# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AnalyzeAndParseTable(self, compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ParsedTable:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeAndParseTable(compressed_text=compressed_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeAndParseTable", args={
                "compressed_text": compressed_text,
            })
            return typing.cast(types.ParsedTable, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def AnalyzeAndParseTableGuided(self, compressed_text: str,visual_schema: types.InferredTableSchema,
        baml_options: BamlCallOptions = {},
    ) -> types.ParsedTable:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeAndParseTableGuided(compressed_text=compressed_text,visual_schema=visual_schema,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeAndParseTableGuided", args={
                "compressed_text": compressed_text,"visual_schema": visual_schema,
            })
            return typing.cast(types.ParsedTable, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DetectAndStructureTable(self, spatial_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DetectedTable:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DetectAndStructureTable(spatial_text=spatial_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DetectAndStructureTable", args={
                "spatial_text": spatial_text,
            })
            return typing.cast(types.DetectedTable, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def InferTableSchemaFromImage(self, page_img: baml_py.Image,compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.InferredTableSchema:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.InferTableSchemaFromImage(page_img=page_img,compressed_text=compressed_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="InferTableSchemaFromImage", args={
                "page_img": page_img,"compressed_text": compressed_text,
            })
            return typing.cast(types.InferredTableSchema, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def InterpretTable(self, compressed_text: str,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MappedTable:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.InterpretTable(compressed_text=compressed_text,schema=schema,model_name=model_name,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="InterpretTable", args={
                "compressed_text": compressed_text,"schema": schema,"model_name": model_name,
            })
            return typing.cast(types.MappedTable, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def MapToCanonicalSchema(self, parsed_table: types.ParsedTable,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MappedTable:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.MapToCanonicalSchema(parsed_table=parsed_table,schema=schema,model_name=model_name,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="MapToCanonicalSchema", args={
                "parsed_table": parsed_table,"schema": schema,"model_name": model_name,
            })
            return typing.cast(types.MappedTable, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def RefineTableHeaders(self, spatial_excerpt: str,data_column_count: int,
        baml_options: BamlCallOptions = {},
    ) -> types.RefinedHeaders:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.RefineTableHeaders(spatial_excerpt=spatial_excerpt,data_column_count=data_column_count,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="RefineTableHeaders", args={
                "spatial_excerpt": spatial_excerpt,"data_column_count": data_column_count,
            })
            return typing.cast(types.RefinedHeaders, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAndParseTable(self, compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ParsedTable, types.ParsedTable]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeAndParseTable", args={
            "compressed_text": compressed_text,
        })
        return baml_py.BamlStream[stream_types.ParsedTable, types.ParsedTable](
          __result__,
          lambda x: typing.cast(stream_types.ParsedTable, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ParsedTable, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyzeAndParseTableGuided(self, compressed_text: str,visual_schema: types.InferredTableSchema,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ParsedTable, types.ParsedTable]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeAndParseTableGuided", args={
            "compressed_text": compressed_text,"visual_schema": visual_schema,
        })
        return baml_py.BamlStream[stream_types.ParsedTable, types.ParsedTable](
          __result__,
          lambda x: typing.cast(stream_types.ParsedTable, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ParsedTable, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetectAndStructureTable(self, spatial_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DetectedTable, types.DetectedTable]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DetectAndStructureTable", args={
            "spatial_text": spatial_text,
        })
        return baml_py.BamlStream[stream_types.DetectedTable, types.DetectedTable](
          __result__,
          lambda x: typing.cast(stream_types.DetectedTable, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DetectedTable, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def InferTableSchemaFromImage(self, page_img: baml_py.Image,compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.InferredTableSchema, types.InferredTableSchema]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="InferTableSchemaFromImage", args={
            "page_img": page_img,"compressed_text": compressed_text,
        })
        return baml_py.BamlStream[stream_types.InferredTableSchema, types.InferredTableSchema](
          __result__,
          lambda x: typing.cast(stream_types.InferredTableSchema, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.InferredTableSchema, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def InterpretTable(self, compressed_text: str,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MappedTable, types.MappedTable]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="InterpretTable", args={
            "compressed_text": compressed_text,"schema": schema,"model_name": model_name,
        })
        return baml_py.BamlStream[stream_types.MappedTable, types.MappedTable](
          __result__,
          lambda x: typing.cast(stream_types.MappedTable, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MappedTable, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MapToCanonicalSchema(self, parsed_table: types.ParsedTable,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MappedTable, types.MappedTable]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="MapToCanonicalSchema", args={
            "parsed_table": parsed_table,"schema": schema,"model_name": model_name,
        })
        return baml_py.BamlStream[stream_types.MappedTable, types.MappedTable](
          __result__,
          lambda x: typing.cast(stream_types.MappedTable, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MappedTable, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RefineTableHeaders(self, spatial_excerpt: str,data_column_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RefinedHeaders, types.RefinedHeaders]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="RefineTableHeaders", args={
            "spatial_excerpt": spatial_excerpt,"data_column_count": data_column_count,
        })
        return baml_py.BamlStream[stream_types.RefinedHeaders, types.RefinedHeaders](
          __result__,
          lambda x: typing.cast(stream_types.RefinedHeaders, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RefinedHeaders, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeAndParseTable(self, compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeAndParseTable", args={
            "compressed_text": compressed_text,
        }, mode="request")
        return __result__
    async def AnalyzeAndParseTableGuided(self, compressed_text: str,visual_schema: types.InferredTableSchema,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeAndParseTableGuided", args={
            "compressed_text": compressed_text,"visual_schema": visual_schema,
        }, mode="request")
        return __result__
    async def DetectAndStructureTable(self, spatial_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectAndStructureTable", args={
            "spatial_text": spatial_text,
        }, mode="request")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    async def InferTableSchemaFromImage(self, page_img: baml_py.Image,compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InferTableSchemaFromImage", args={
            "page_img": page_img,"compressed_text": compressed_text,
        }, mode="request")
        return __result__
    async def InterpretTable(self, compressed_text: str,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InterpretTable", args={
            "compressed_text": compressed_text,"schema": schema,"model_name": model_name,
        }, mode="request")
        return __result__
    async def MapToCanonicalSchema(self, parsed_table: types.ParsedTable,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MapToCanonicalSchema", args={
            "parsed_table": parsed_table,"schema": schema,"model_name": model_name,
        }, mode="request")
        return __result__
    async def RefineTableHeaders(self, spatial_excerpt: str,data_column_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RefineTableHeaders", args={
            "spatial_excerpt": spatial_excerpt,"data_column_count": data_column_count,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeAndParseTable(self, compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeAndParseTable", args={
            "compressed_text": compressed_text,
        }, mode="stream")
        return __result__
    async def AnalyzeAndParseTableGuided(self, compressed_text: str,visual_schema: types.InferredTableSchema,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeAndParseTableGuided", args={
            "compressed_text": compressed_text,"visual_schema": visual_schema,
        }, mode="stream")
        return __result__
    async def DetectAndStructureTable(self, spatial_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectAndStructureTable", args={
            "spatial_text": spatial_text,
        }, mode="stream")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    async def InferTableSchemaFromImage(self, page_img: baml_py.Image,compressed_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InferTableSchemaFromImage", args={
            "page_img": page_img,"compressed_text": compressed_text,
        }, mode="stream")
        return __result__
    async def InterpretTable(self, compressed_text: str,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InterpretTable", args={
            "compressed_text": compressed_text,"schema": schema,"model_name": model_name,
        }, mode="stream")
        return __result__
    async def MapToCanonicalSchema(self, parsed_table: types.ParsedTable,schema: types.CanonicalSchema,model_name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MapToCanonicalSchema", args={
            "parsed_table": parsed_table,"schema": schema,"model_name": model_name,
        }, mode="stream")
        return __result__
    async def RefineTableHeaders(self, spatial_excerpt: str,data_column_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RefineTableHeaders", args={
            "spatial_excerpt": spatial_excerpt,"data_column_count": data_column_count,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))