# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAndParseTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ParsedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAndParseTable", llm_response=llm_response, mode="request")
        return typing.cast(types.ParsedTable, __result__)

    def AnalyzeAndParseTableGuided(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ParsedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAndParseTableGuided", llm_response=llm_response, mode="request")
        return typing.cast(types.ParsedTable, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def InferTableSchemaFromImage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InferredTableSchema:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InferTableSchemaFromImage", llm_response=llm_response, mode="request")
        return typing.cast(types.InferredTableSchema, __result__)

    def InterpretTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MappedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InterpretTable", llm_response=llm_response, mode="request")
        return typing.cast(types.MappedTable, __result__)

    def MapToCanonicalSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MappedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapToCanonicalSchema", llm_response=llm_response, mode="request")
        return typing.cast(types.MappedTable, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAndParseTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ParsedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAndParseTable", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ParsedTable, __result__)

    def AnalyzeAndParseTableGuided(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ParsedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAndParseTableGuided", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ParsedTable, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def InferTableSchemaFromImage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InferredTableSchema:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InferTableSchemaFromImage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InferredTableSchema, __result__)

    def InterpretTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MappedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InterpretTable", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MappedTable, __result__)

    def MapToCanonicalSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MappedTable:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapToCanonicalSchema", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MappedTable, __result__)

    